# Generated by Django 5.2.1 on 2025-06-13 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examquestion',
            name='correct_option',
        ),
        migrations.RemoveField(
            model_name='examquestion',
            name='option_a',
        ),
        migrations.RemoveField(
            model_name='examquestion',
            name='option_b',
        ),
        migrations.RemoveField(
            model_name='examquestion',
            name='option_c',
        ),
        migrations.RemoveField(
            model_name='examquestion',
            name='option_d',
        ),
        migrations.RemoveField(
            model_name='examquestion',
            name='question_text',
        ),
        migrations.AddField(
            model_name='examquestion',
            name='encrypted_correct_option',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='encrypted_option_a',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='encrypted_option_b',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='encrypted_option_c',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='encrypted_option_d',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='encrypted_question_text',
            field=models.BinaryField(default=b''),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='exam',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.exam'),
        ),
    ]
