# Generated by Django 5.2.1 on 2025-06-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_examquestion_correct_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
